# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('type', models.SmallIntegerField(choices=[(1, 'Food'), (2, 'Entertainment'), (3, 'Rent'), (4, 'Other')], default=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
